# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Executa a ação em qualquer push na branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step para configurar o GitHub Pages para usar a branch main e o caminho root
      - name: Configure GitHub Pages to use branch 'main' and path 'root'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          curl -X PATCH \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/pages \
            -d "{\"source\": {\"branch\": \"main\", \"path\": \"/\"}}"

      # Opcional: Faça o build do site se necessário
      # Exemplo para um projeto com site estático gerado (substitua pelo seu comando de build)
      - name: Build site
        run: |
          # Se você tiver um comando de build, coloque aqui, por exemplo:
          # npm install && npm run build
          echo "Build completed"

      # Commit e push para a branch 'main' (caso precise)
      - name: Push changes to main
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add -A
          git commit -m "Automated commit for GitHub Pages deploy" || echo "No changes to commit"
          git push origin main
